version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Awayume"
    open-pull-requests-limit: 10
    reviewers:
      - "Awayume"
    target-branch: "main"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Awayume"
    open-pull-requests-limit: 10
    reviewers:
      - "Awayume"
    target-branch: "main"
