name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: unconfirmed bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to improve SoarWings.

  - type: input
    attributes:
      label: Summary
      description: Please give a brief summary of the report.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the bug
      description: Please describe the steps to reproduce the bug in as much detail as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Code to reproduce the bug
      description: |
        Please post the code that reproduces the bug.
        Don't omit use declarations in your code.
      render: rust
    validations:
      required: true

  - type: textarea
    attributes:
      label: Desired result
      description: What is the result of the code above if the bug does not occur?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual result
      description: What are the consequences of the above code due to the bug?
    validations:
      required: true

  - type: input
    attributes:
      label: Bug reproducibility
      description: Calculate the reproducibility of the bug and enter it as a percentage.
    validations:
      required: true

  - type: textarea
    attributes:
      label: System information
      description: OS version and model name.
    validations:
      required: true

  - type: input
    attributes:
      label: Twitter version
      description: The version of Twitter to be patched.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: SoarWings version
      description: Choose your version of SoarWings.
      options:
        - 0.1.0 (Alpha)
    validations:
      required: true

  - type: input
    attributes:
      label: SoarWings commit hash
      description: If you're using an unreleased version (alpha, beta, rc, etc.), write the Disorust commit hash.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional information
      description: Please write if you have anything else to say.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      description: This is the final confirmation of the report.
      options:
        - label: I follow the contribution guidelines.
          required: true
        - label: I confirmed that there is no similar issue.
          required: true
        - label: I have checked that this issue does not contain any credentials or personal informations.
          required: true
