name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.git*'
      - '.github/**'
      - '!.github/workflows/test.yaml'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/
            .gradle/
          key: ${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            app/build/
          key: ${{ hashFiles('app/build.gradle') }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: |
          touch local.properties
          ./gradlew test
