name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.git*'
      - '.github/**'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/dists
          key: ${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: |
          ./gradlew test
